apiVersion: apps/v1
kind: Deployment
metadata:
  name: ray
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ray
  template:
    metadata:
      labels:
        app: ray
    spec:
      containers:
      - image: okteto.dev/ray:latest
        name: ray
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: ""
        - name: Vless_UUID
          value: "b03b30c6-349e-4ebd-b418-f1977468a030"
        - name: Vless_Path
          value: "/ugyu"
        - name: Vmess_UUID
          value: "b03b30c6-349e-4ebd-b418-f1977468a030"
        - name: Vmess_Path
          value: "/jphu"
        - name: Share_Path
          value: "/share233"
